api/config/routes.rb
Rails.application.routes.draw do
  resources :aims
end

api/app/models/aim.rb
class Aim < ApplicationRecord
  validates :title, presence: true
end

api/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

api/app/controllers/aims_controller.rb
class AimsController < ApplicationController
  before_action :set_aim, only: [:show, :edit, :update, :destroy]

  def index
    @q = Aim.ransack(params[:q])
    @aims = @q.result.page(params[:page]).per(5)
  end

  def show
  end
  
  

  def new
    @aim = Aim.new
  end

  def create
    @aim = Aim.new(aim_params)
    if @aim.save
      flash[:success] = '目標を作成しました'
      redirect_to aims_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @aim.update(aim_params)
      flash[:success] = "目標を更新しました"
      redirect_to aim_path(@aim.id)
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @aim.destroy
    flash[:success] = '目標を削除しました'
    redirect_to aims_path
  end

  private

    def set_aim
      @aim = Aim.find(params[:id])
    end

   def aim_params
    params.require(:aim).permit(:title, :reason, :advantage, :difficulty)
   end

   def print_hello
     puts 'hello world'
   end
end

api/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

api/app/helpers/aims_helper.rb
module AimsHelper
end

api/app/helpers/application_helper.rb
module ApplicationHelper
end

api/app/views/aims/_form.html.erb
<%= form_with(model: @aim, local: true) do |f| %>
  <%= render "shared/error_messages", model: @aim %>
  <div class="form-group mb-3">
    <%= f.label :title, '目標名', class: 'form-label background-color' %>
    <%= f.text_field :title, class: 'form-control', readonly: action==='show' %>
  </div>

  <div class="form-group mb-3">
    <%= f.label :reason, '理由', class: 'form-label background-color' %>
    <%= f.text_area :reason, class: 'form-control', readonly: action==='show' %>
  </div>

  <div class="form-group mb-3">
    <%= f.label :advantage, '得られるもの', class: 'form-label background-color' %>
    <%= f.text_area :advantage, class: 'form-control', readonly: action==='show' %>
  </div>

  <div class="form-group mb-3">
    <%= f.label :difficulty, '難易度', class: 'form-label background-color' %>
    <%= f.text_field :difficulty, class: 'form-control', readonly: action==='show' %>
  </div>

  <div class="form-group mb-3">
    <% if action==='show' %>
      <%= link_to '編集', edit_aim_path(@aim.id), class: 'btn btn-primary' %>
    <% else %>
      <%= f.submit "#{ @aim.new_record? ? '新規作成' : '更新' }", class: 'mt-3 btn btn-primary' %>
    <% end %>
  </div>
<% end %>

api/app/views/aims/edit.html.erb
<%= render partial: "form", locals: {action: 'edit'} %>

api/app/views/aims/index.html.erb
<% provide(:title, t('title.aim.index')) %>
<h3 class="mt-3 text-center">目標一覧</h3>

<div class="d-flex justify-content-end">
  <%= link_to "新規作成", new_aim_path, class: 'mb-3 btn btn-primary' %>
</div>

<%= search_form_for @q, class: 'row g-3', url: aims_path do |f| %>
  <div class="col-md-4">
    <%= f.label :title_cont, '目標名', class: 'form-label' %>
    <%= f.search_field :title_cont, class: 'form-control' %>
    <br>
  </div>

  <div class="col-md-4">
    <%= f.label :reason_cont, '理由', class: 'form-label' %>
    <%= f.text_area :reason_cont, class: 'form-control' %>

  </div>

  <div class="col-md-4">
    <%= f.label :advantage_cont, '得られるもの', class: 'form-label' %>
    <%= f.text_area :advantage_cont, class: 'form-control' %>

    <%= f.label :difficulty_cont, '難易度', class: 'form-label' %>
    <%= f.search_field :difficulty_cont, class: 'form-control' %>
  </div>
  <div class="d-flex justify-content-center mb-3">
    <%= f.submit "クリア", type: :reset, class: 'btn btn-light' %>
    <%= f.submit '検索', class: 'btn btn-primary' %>
  </div>
<% end %>

<table class="mt-3 table table-bordered">
  <tr>
    <th><%= sort_link(@q, :title, '目標名', class: 'nav-link') %></th>
    <th><%= sort_link(@q, :reason, '理由', class: 'nav-link') %></th>
    <th><%= sort_link(@q, :advantage, '利点', class: 'nav-link') %></th>
    <th><%= sort_link(@q, :difficulty, '難易度', class: 'nav-link') %></th>
    <th>編集</th>
    <th>削除</th>
  </tr>
  <% @aims.each do |aim| %>
    <tr>
      <td><%= link_to aim.title, aim_path(aim), class: 'nav-link' %></td>
      <td><%= aim.reason %></td>
      <td><%= aim.advantage %></td>
      <td><%= t("enum.aim.difficulty.#{aim.difficulty}") %></td>
      <td><%= link_to '編集', edit_aim_path(aim.id), class: 'btn btn-primary' %></td>
      <td><%= button_to '削除', aim_path(aim.id), method: :delete, form:{ data: { turbo_confirm: "目標を削除します。よろしいですか？" }}, class: 'btn btn-danger' %></td>
    </tr>
  <% end %>
</table>
<%= paginate @aims %>

api/app/views/aims/new.html.erb
<%= render partial: "form", locals: {action: 'new'} %>

api/app/views/aims/show.html.erb
<%= render partial: "form", locals: {action: 'show'} %>

api/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

     <% flash.each do |status, message| %>
      <div>
        <%= message %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

api/app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <% model.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
<% end %>